### PR TITLE
Required Level added to Runewizard 

### PR DESCRIPTION
**Pull request by magouill**
Added Required Level to Runewizard

### CODE REVIEW

**Comment by magouill** [comment]
Just note that I haven't tested any of theses changes when hosting on Github.io

**Comment by fabd** [comment]
Hello there!

This doesn't work as is.

For testing ; assuming you want to keep poking it ; you need to [install Jekyll](https://jekyllrb.com/docs/installation/). Then you can do `jekyll serve --watch` and youĺl be able to preview the site as it is served by github, locally (the url will be something like `http://127.0.0.1:4000/diablo2/runewizard/`). 

That said, when I tried even my `master` branch, runewizard broke. The css/js were not included because one of the conditionals in the default.html no longer works.. maybe it is due to  a recent jekyll install I have no idea. The conditional needs to be `{% if page.url == "/runewizard/" %}`.

When that is done the table doesn't display properly. You have to also edit `main.js`. The code I wrote back then is pretty awful, it refernces column with more or less hardcoded values like `this.MAX_RUNES+2`.

Anyways, I fixed main.js, is this what you are looking for?

runewords-fix

I guess it can be useful to sort by required level though back when I played I found there's only a handful you can make at low level easily, and by the time you get runes to make the really good ones, you're already in Hell difficulty :)

So at first I thought maybe I'd prefer to add "Required Level" as part of the runewords popups, but I guess adding one small column to the table is also fine, this lets you sort the Runewords by level.

If I have time I'd like to rewrite this with VueJS, would make a lot more sense and simpler to edit. We'll see.

I guess I may as well push the changes I made locally, including your commits, since you spent some time adding the levels in there. Let me know if the picture above is what you wanted.

I'll see if I can push the changes this afternoon.

**Comment by magouill** [comment]
Hello there,
Great to see you going back to this after 7 years haha.

Yes the picture you've shared is exactly what I was looking for Diablo 2
If you need anything else from me please let me know. I would love to see
that happening.

**Comment by fabd** [comment]
@migouelBL It looks like you tried adding level into the Runes.txt file. I will have to ignore those changes. Those are the spreadsheet style datafiles straight out of the game's data files, used by the scripts. You can't change the meaning of a column in there, and even assuming  you wanted to update the Perl scritps that parse this data, then you'd want to make a new data file otherwise when a new patch comes that did some gameplay updates, we'd extract the new datafiles and overwrite whatever was changed locally.

Runewizard doesn't use these files in any case. I guess I could have but there aren't so much data for the runewords alone, so I entered the Runewords data manually, and Runwewizard is more stand alone (could realistically made into its own little webpage or even a little ios app). The `Item Bonuses` page does parse those files, but it doesn't need the level information.

**Comment by fabd** [comment]
I mostly just need the level data you inputted in main.js. No need to update the commits, I should be able to merge the relevant ones into the master branch.

**Comment by magouill** [comment]
Aw good to know. Ok. I thought someone had made this text file.

**Comment by fabd** [comment]
I'm sorry I'm not proficient with git enough to handle merging the pull request as is, I don't have a easy way of canceling the Runes.txt commit.

I did some cherry-picks from your PR branch, and merged into master maintaining the auhor information.

Looking into having the Github pages update.

**Comment by fabd** [comment]
PS: the online version is updated.

I changed the URLs to remove the `.html`extensions so they are shorter, this may cause old bookmarks to break.

http://fabd.github.io/diablo2/runewizard/

**Comment by fabd** [comment]
Hi @migouelBL 

Happy to let you know Runewizard has a [new repo](https://github.com/fabd/diablo2-runewizard), completey rewritten in modern Javascript.

As it is a new repo I haven't been able to maintain your PR. Thanks again for providing the required levels data!

Should you find any incorrect data or maybe a typo in the [new live version of Runewizard](https://fabd.github.io/diablo2-runewizard/), please let me know. The new version data files are in [/src/data/](https://github.com/fabd/diablo2-runewizard/tree/main/src/data) folder.

**Pull request closed without merging**
